# remap prefix from 'C-b' to 'C-Space'
unbind C-b
unbind C-a
set-option -g prefix C-a
bind-key C-a send-prefix

#my custom bindings
bind v new-window -c "#{pane_current_path}"
set-option -g renumber-windows on
bind a copy-mode
set-option -g detach-on-destroy off
bind c new-window -c "$HOME"
bind-key -T copy-mode-vi v send -X begin-selection
set -s escape-time 0
set -g base-index 1
set -g status-interval 1
set -sg escape-time 0

bind q clear-history
bind -n C-S-Left { swap-window -t -1; previous-window }
bind -n C-S-Right { swap-window -t +1; next-window }
unbind ' '

# start with window 1 (instead of 0)
set -g base-index 1


# start with pane 1
set -g pane-base-index 1


# screen mode
set -g default-terminal 'xterm-256color'

# source config file
bind r source-file ~/.tmux.conf


# history
set -g history-limit 10000


# allow terminal scrolling
set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'

# use vi mode
setw -g mode-keys vi
set -g status-keys vi


# tmux-zoom.sh
#bind C-z run "tmux-zoom.sh"

# easy-to-remember split pane commands
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
#unbind '"'
#unbind %


# colon :
bind : command-prompt


# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize the pane
bind-key -r J resize-pane -D 3
bind-key -r K resize-pane -U 3
bind-key -r H resize-pane -L 3
bind-key -r L resize-pane -R 3


# Info on left (I don't have a session display for now)
set -g status-left ''


# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-window-option -g mode-keys vi
set-option -g bell-action none


# some key-binding changes
#bind x kill-pane
#bind X next-layout
#bind Z previous-layout

#urxvt tab like window switching (-n: no prior escape seq)
#bind -n S-down new-window
#bind -n S-left prev
#bind -n S-right next
#bind -n C-left swap-window -t -1
#bind -n C-right swap-window -t +1

# The statusbar {
set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-left ''
set -g status-right '#[fg=colour245,bold]#(cd #{pane_current_path}; git describe --exact-match --tags) #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) #[fg=colour233,bg=colour241,bold] %m/%d #[fg=colour233,bg=colour245,bold] %H:%M '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jabirali/tmux-tilish'
set -g @plugin 'sunaku/tmux-navigate'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @tilish-navigate 'on'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

unbind-key -n M-o; unbind-key -n M-S-o
unbind-key -n M-Enter
unbind-key -n M-s; unbind-key -n M-S-s
unbind-key -n M-v; unbind-key -n M-S-v
unbind-key -n M-t; unbind-key -n M-r

unbind-key -n M-n; unbind-key -n M-d; unbind-key -n M-p
unbind-key -n M-S-q; unbind-key -n M-S-e; unbind-key -n M-S-c

unbind-key -n M-0;
unbind-key -n M-1;
unbind-key -n M-2;
unbind-key -n M-3;
unbind-key -n M-4;
unbind-key -n M-5;
unbind-key -n M-6;
unbind-key -n M-7;
unbind-key -n M-8;
unbind-key -n M-9;
